plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.gradle.userdev' version '7.0.97'
	id 'net.neoforged.gradle.mixin' version '7.0.97'
}

def stdout = new ByteArrayOutputStream()
exec {
	commandLine 'git', 'rev-parse', '--short', 'HEAD'
	standardOutput = stdout
}
def commit = stdout.toString().replace("\n", "").replace("\r", "").trim()

version = project.hasProperty("dev") ? commit : mod_version

repositories {
	mavenLocal()
	maven {
		// JEI
		url "https://maven.blamejared.com/"
	}
	maven {
		// JEI fallback
		url "https://modmaven.dev"
	}
	maven {
		url "https://cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	maven {
		url "https://maven2.bai.lol"
		content {
			includeGroup "lol.bai"
			includeGroup "mcp.mobius.waila"
		}
	}
	maven {
		url "https://maven.shedaniel.me/"
	}
}

base {
	archivesName = project.projectDir.name + "-mc${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

runs {
	configureEach {
		systemProperty 'forge.logging.markers', 'REGISTRIES'
		systemProperty 'forge.logging.console.level', 'debug'

		modSource project.sourceSets.main
	}

	client {
		systemProperty 'forge.enabledGameTestNamespaces', 'veganoption'
	}

	server {
		systemProperty 'forge.enabledGameTestNamespaces', 'veganoption'
		programArgument '--nogui'
	}

	gameTestServer {
		systemProperty 'forge.enabledGameTestNamespaces', 'veganoption'
	}

	data {
		programArguments.addAll '--mod', 'veganoption', '--all', '--output', file('generated/resources/').getAbsolutePath(),
				'--existing', file('resources/').getAbsolutePath()
	}
}

minecraft.accessTransformers.file rootProject.file('resources/META-INF/accesstransformer.cfg')

sourceSets.main.java.srcDirs += 'java'
sourceSets.main.java.srcDirs += 'apis'
sourceSets.main.resources.srcDirs += 'resources'
sourceSets.main.resources.srcDirs += 'generated/resources'
sourceSets.test.java.srcDirs += 'tests'
 
dependencies {
	implementation "net.neoforged:neoforge:${neoforge_version}"
	implementation "curse.maven:jade-324717:${jade_version}"
	// REI is using an old version of Architectury which had not yet been updated for NeoForge 20.4.70+.
	implementation "dev.architectury:architectury-neoforge:${architectury_version_override}"
	// We need the default implementations in REI, rather than just the API
	implementation("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}") {
		// Only use our version
		exclude group: "dev.architectury"
	}

	compileOnly "mcp.mobius.waila:wthit-api:neo-${wthit_version}"

	runtimeOnly "mcp.mobius.waila:wthit:neo-${wthit_version}"
	runtimeOnly "lol.bai:badpackets:neo-${badpackets_version}"

//	Awaiting a NeoForge version...
//	compileOnly "mezz.jei:jei-1.20.2-common-api:${jei_version}"
//	compileOnly "mezz.jei:jei-1.20.2-forge-api:${jei_version}"
//	runtimeOnly "mezz.jei:jei-1.20.2-forge:${jei_version}"
}

subsystems {
	parchment {
		minecraftVersion = parchment_mc_version
		mappingsVersion = parchment_mappings_version
	}
}

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
			minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
			neo_version: neoforge_version, neo_version_range: neoforge_version_range,
			loader_version_range: loader_version_range,
			mod_id: "veganoption",
			mod_name: "The Vegan Option",
			mod_license: "Public Domain",
			mod_version: project.version,
			mod_authors: "squeek502, SatanicSanta",
			mod_description: "Adds vegan alternatives for the various animal products used in Minecraft.",
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
		expand replaceProperties + [project: project]
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}